### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by leaf403** [bambosan/BSBE-Lite#14]
- The water reflection looks odd when it's on waterfall form (Idk how to explain it)
- You can still see the sky on the water reflection when inside houses/builds

![Screenshot_(163)](https://user-images.githubusercontent.com/108045150/180655659-19a5def3-0842-4d41-9b23-7582a80bd92e.png)
![Screenshot_(164)](https://user-images.githubusercontent.com/108045150/180655661-1bd9435d-a661-4c3e-84e1-c1b16202223c.png)

**Comment by bambosan** [comment]
no
ah maybe I forgot about that, sorry
I will fix it in the next update
thank for report it!
