### ISSUE TITLE
Issues with Intel GPU

### ISSUE THREAD

**Issue by shizotoaster** [bambosan/BSBE-Lite#2]
Everything is invisible on my Intel GPU
![Screenshot_20210823_141220](https://user-images.githubusercontent.com/51480483/130405868-1e51f374-5f43-49f4-bce5-6af0b99d3e4a.png)
OS: Linux
GPU: Intel HD Graphics 520

**Comment by bambosan** [comment]
actually i don't know how to solve it because so far i've only tried my shaders on mobile phone gpu, but maybe I'll figure out how to fix that
